name: 'LibGDX Build and Deploy'
on:
  push:
    branches: main
jobs:
  windows:
    name: windows build and deploy
    runs-on: [self-hosted, windows]
    defaults:
      run:
        working-directory: temp
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ secrets.GAME_NAME }}
      - name: Clean temp directory
        run: rm -rf *
        working-directory: ./temp
  linux:
    name: linux build and deploy
    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: temp
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ secrets.GAME_NAME }}
      - name: Clean temp directory
        run: rm -rf *
        working-directory: ./temp
  mac:
    name: mac build and deploy
    runs-on: [self-hosted, mac]
    defaults:
      run:
        working-directory: temp
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ secrets.GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ secrets.GAME_NAME }}
      - name: Clean temp directory
        run: rm -rf *
        working-directory: ./temp