name: 'LibGDX Build and Deploy'
description: 'GitHub action that builds LibGDX executable and deploys'

on:
  push:
    branches: main

jobs:
  windows:
    name: windows build and deploy
    runs-on: [self-hosted, windows]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
        shell: bash
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ GAME_NAME }}
  linux:
    name: linux build and deploy
    runs-on: [self-hosted, linux]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
        shell: bash
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ GAME_NAME }}
  mac:
    name: mac build and deploy
    runs-on: [self-hosted, mac]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build
        run: gradlew jpackageImage
        shell: bash
      - name: Itch.io Push
        uses: josephbmanley/butler-publish-itchio-action@master
        with:
          BUTLER_CREDENTIALS: ${{ BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ GAME_NAME }}
          ITCH_USER: freebrunch
          PACKAGE: ./lwjgl3/build/jpackage/${{ GAME_NAME }}